[2023-10-11 12:19:20,131] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: scrape_google.scrape_and_save 2023-10-11T12:19:17.405409+00:00 [queued]>
[2023-10-11 12:19:20,152] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: scrape_google.scrape_and_save 2023-10-11T12:19:17.405409+00:00 [queued]>
[2023-10-11 12:19:20,153] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 12:19:20,156] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2023-10-11 12:19:20,161] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2023-10-11 12:19:20,181] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): scrape_and_save> on 2023-10-11T12:19:17.405409+00:00
[2023-10-11 12:19:20,192] {standard_task_runner.py:52} INFO - Started process 270 to run task
[2023-10-11 12:19:20,202] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scrape_google', 'scrape_and_save', '2023-10-11T12:19:17.405409+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/scrap_test_dag.py', '--cfg-path', '/tmp/tmpx27lbiy0', '--error-file', '/tmp/tmp5kwsmpwu']
[2023-10-11 12:19:20,207] {standard_task_runner.py:77} INFO - Job 24: Subtask scrape_and_save
[2023-10-11 12:19:20,277] {logging_mixin.py:104} INFO - Running <TaskInstance: scrape_google.scrape_and_save 2023-10-11T12:19:17.405409+00:00 [running]> on host 62cfcfb44bb5
[2023-10-11 12:19:20,390] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=you
AIRFLOW_CTX_DAG_ID=scrape_google
AIRFLOW_CTX_TASK_ID=scrape_and_save
AIRFLOW_CTX_EXECUTION_DATE=2023-10-11T12:19:17.405409+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-11T12:19:17.405409+00:00
[2023-10-11 12:19:21,284] {logging_mixin.py:104} INFO - > /opt/***/dags/scrap_test_dag.py(21)scrape_google()
-> if not os.path.exists(OUTPUT_DIR):
[2023-10-11 12:19:21,286] {logging_mixin.py:104} INFO - (Pdb) 
[2023-10-11 12:19:21,288] {logging_mixin.py:104} INFO - 
[2023-10-11 12:19:21,290] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scrap_test_dag.py", line 21, in scrape_google
    if not os.path.exists(OUTPUT_DIR):
  File "/opt/airflow/dags/scrap_test_dag.py", line 21, in scrape_google
    if not os.path.exists(OUTPUT_DIR):
  File "/usr/local/lib/python3.6/bdb.py", line 51, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/lib/python3.6/bdb.py", line 70, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
[2023-10-11 12:19:21,297] {taskinstance.py:1531} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_google, task_id=scrape_and_save, execution_date=20231011T121917, start_date=20231011T121920, end_date=20231011T121921
[2023-10-11 12:19:21,381] {local_task_job.py:151} INFO - Task exited with return code 1
