[2023-10-10 17:30:13,718] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: write_json_test.write_json 2023-10-10T17:25:09.914441+00:00 [queued]>
[2023-10-10 17:30:13,733] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: write_json_test.write_json 2023-10-10T17:25:09.914441+00:00 [queued]>
[2023-10-10 17:30:13,735] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2023-10-10 17:30:13,737] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2023-10-10 17:30:13,738] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2023-10-10 17:30:13,761] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): write_json> on 2023-10-10T17:25:09.914441+00:00
[2023-10-10 17:30:13,768] {standard_task_runner.py:52} INFO - Started process 1001 to run task
[2023-10-10 17:30:13,775] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'write_json_test', 'write_json', '2023-10-10T17:25:09.914441+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dummy_dag.py', '--cfg-path', '/tmp/tmpsnh6ywhp', '--error-file', '/tmp/tmpctqwdazb']
[2023-10-10 17:30:13,779] {standard_task_runner.py:77} INFO - Job 5: Subtask write_json
[2023-10-10 17:30:13,851] {logging_mixin.py:104} INFO - Running <TaskInstance: write_json_test.write_json 2023-10-10T17:25:09.914441+00:00 [running]> on host 639abfbfd4e2
[2023-10-10 17:30:13,926] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=you
AIRFLOW_CTX_DAG_ID=write_json_test
AIRFLOW_CTX_TASK_ID=write_json
AIRFLOW_CTX_EXECUTION_DATE=2023-10-10T17:25:09.914441+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-10T17:25:09.914441+00:00
[2023-10-10 17:30:13,930] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dummy_dag.py", line 35, in write_json_file
    os.makedirs(dir_path)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/path_in_container/'
[2023-10-10 17:30:13,938] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=write_json_test, task_id=write_json, execution_date=20231010T172509, start_date=20231010T173013, end_date=20231010T173013
[2023-10-10 17:30:13,995] {local_task_job.py:151} INFO - Task exited with return code 1
